services:
  db:
    image: postgres:15
    container_name: deposit_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: C9fdlsxf4!
      POSTGRES_DB: deposit_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build:
      context: .
    container_name: deposit_calculator_app
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:C9fdlsxf4!@db/deposit_db
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - .:/app
    command: >
      bash -c "alembic -c alembic/alembic.ini upgrade head && uvicorn src.main:app --host 0.0.0.0 --port 8000"


volumes:
  db_data:
